apiVersion: v1
kind: ConfigMap
metadata:
  name: ecograd-config
  namespace: ecograd
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://ecograd-db-service:5432/ecoGrad
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_DATASOURCE_HIKARI_CONNECTIONTIMEOUT: "20000"
  SPRING_DATASOURCE_HIKARI_MAXIMUMPOOLSIZE: "5"
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
  SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_LOB_NON_CONTEXTUAL_CREATION: "true"
  SPRING_JPA_SHOW_SQL: "true"