apiVersion: v1
kind: ConfigMap
metadata:
  name: eco-grad-app-config
  namespace: eco-grad
data:
  application.properties: |
    server.port=8080
    spring.security.oauth2.client.registration.github.client-id=<6906300af766548b4ea4>
    spring.security.oauth2.client.registration.github.client-secret=<5648241d9c546f51ae2db617f96844735474bc83>
    logging.level.org.springframework.security=TRACE

    ## PostgreSQL
    spring.datasource.url=jdbc:postgresql://eco-grad-db:5432/ecoGrad
    spring.datasource.username=<base64-encoded-username>
    spring.datasource.password=<base64-encoded-password>
    ## default connection pool
    spring.datasource.hikari.connectionTimeout=20000
    spring.datasource.hikari.maximumPoolSize=5
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true
