version: "3.7"
services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ecoGrad
      POSTGRES_PASSWORD: metallica
      POSTGRES_USER: postgres
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ecoGrad
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=metallica
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: unless-stopped
    ports:
      - "80:8080"

volumes:
  db-data: