version: "3.7"
services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ecoGrad
      POSTGRES_PASSWORD: metallica
      POSTGRES_USER: postgres
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: metallica
      DB_NAME: ecoGrad
    restart: unless-stopped
    ports:
      - "80:8080"

volumes:
  db-data: