apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eco-grad-db
  namespace: eco-grad
spec:
  serviceName: eco-grad-db
  replicas: 1
  selector:
    matchLabels:
      app: eco-grad-db
  template:
    metadata:
      labels:
        app: eco-grad-db
    spec:
      containers:
      - name: eco-grad-db
        image: postgres:latest
        env:
        - name: POSTGRES_DB
          value: ecoGrad
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: eco-grad-db-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: eco-grad-db-secret
              key: password
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: eco-grad-db
  namespace: eco-grad
spec:
  selector:
    app: eco-grad-db
  ports:
    - protocol: TCP
      port: 5432
