name: CI CD pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t tamarakostova/ecograd:latest .

      - name: Push Docker image to DockerHub
        run: docker push tamarakostova/ecograd:latest

  notify:
    if: always()
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: ecograd-app
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: 'Deployment done!'
          SLACK_USERNAME: Tamara Kostova
